# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name1', models.CharField(max_length=50)),
                ('first_name1', models.CharField(max_length=50)),
                ('last_name2', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name2', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=50, unique=True)),
                ('house_number', models.IntegerField()),
                ('street_name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OWNED', 'Owned by Owner'), ('SALE', 'On Sale'), ('UNKNOWN', 'Unknown')], default='OWNED', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('PAST_DUE', 'Past Due')], default='PENDING', max_length=10)),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('amount_pending', models.DecimalField(decimal_places=2, max_digits=8)),
                ('homeowner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoice.Household')),
            ],
        ),
    ]
