# Generated by Django 2.0.dev20170318191452 on 2017-08-03 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('last_name1', models.CharField(max_length=50)),
                ('first_name1', models.CharField(max_length=50)),
                ('last_name2', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name2', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('house_number', models.IntegerField()),
                ('street_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Paid', 'PAID'), ('Pending', 'PENDING'), ('Past Due', 'PAST_DUE')], max_length=10)),
                ('date_issued', models.DateField()),
                ('amount_pending', models.DecimalField(decimal_places=2, max_digits=8)),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoice.Household')),
            ],
        ),
    ]
