# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='agent_email_status',
            field=models.CharField(blank=True, choices=[('SENT', 'Sent to Agent')], max_length=20, null=True),
        ),
    ]
