# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_household_agent_email_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='agent_email_status',
            field=models.CharField(choices=[('SENT', 'Sent to Agent'), ('NOT SENT', 'Not Sent to Agent')], default='NOT SENT', max_length=20),
        ),
    ]
