# Generated by Django 2.0.dev20170318191452 on 2017-08-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20170803_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='status',
            field=models.CharField(choices=[('OWNED', 'Owned by Owner'), ('SALE', 'On Sale'), ('UNKNOWN', 'Unknown')], default='OWNED', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('PAST_DUE', 'Past Due')], default='PENDING', max_length=10),
        ),
    ]
